const URL_CONEXION = 'http://localhost:3000/';
const URL_API = 'api/';

// Sesion
const BASE_SESION = 'sesiones/';
const URL_INICIAR_SESION = 'iniciar/';
const URL_CERRAR_SESION = 'salir/';

// Llaves Async Storage
const USUARIO_SESION = 'usuarioSesion';
const CBOTIPOEMPLEADO = 'CBOTIPOEMPLEADO';
const CBOJORNADA = 'CBOJORNADA';
const CBOROL = 'CBOROL';
const OPCIONMENU = 'OPCIONMENU';
const COMBOSCONSULTADOS = 'COMBOSCONSULTADOS';
const OBTENEREMPLEADOS = 'OBTENEREMPLEADOS';
const EMPLEADOSCONSULTADOS = 'EMPLEADOSCONSULTADOS';
const IDEMPLEADO = 'IDEMPLEADO';
const OBTENERBONOENTREGAS = 'OBTENERBONOENTREGAS';
const OBTNERMOVIMIENTOS = 'OBTNERMOVIMIENTOS';
const MOVIMIENTOSCONSULTADOS = 'MOVIMIENTOSCONSULTADOS';
const IDMOVIMIENTO = 'IDMOVIMIENTO';
const DATOS_REPORTE = 'DATOS_REPORTE';

//Empleados
const BASE_EMPLEADO = 'empleados/';
const URL_EMPLEADOID = 'empleadoId/';
const URL_REPORTE = 'reporte/';
const URL_IDSIGUIENTE = 'siguienteId';

//Tipo Empleado
const BASE_TIPO_EMPLEADO = 'tipoEmpleado/';

//Jornada Laboral
const BASE_JORNADA_LABORAL = 'jornadaLaboral/';

//ROl
const BASE_ROL = 'rol/';


//ROL AUXILIAR
const ROL_AUXILIAR = 3;

//Movimientos
const BASE_MOVIMIENTOS = 'movimientos/';
const URL_MOVIMIENTOID = 'movimientoId/';
const URL_FECHAMOVIMIENTO = 'movimientoFecha/'

//Tipo BONO
const BASE_TIPOBONO = 'tipoBono/';
const URL_TIPOBONO = 'bono/';

//TIPOBONO 
const BONOPORENTREGA = 'BonoPorEntrega';


export {
    URL_CONEXION,
    URL_API,
    BASE_SESION,
    URL_INICIAR_SESION,
    URL_CERRAR_SESION,
    USUARIO_SESION,
    BASE_EMPLEADO,
    BASE_TIPO_EMPLEADO,
    BASE_JORNADA_LABORAL,
    BASE_ROL,
    CBOTIPOEMPLEADO,
    CBOJORNADA,
    CBOROL,
    OPCIONMENU,
    COMBOSCONSULTADOS,
    OBTENEREMPLEADOS,
    EMPLEADOSCONSULTADOS,
    IDEMPLEADO,
    URL_EMPLEADOID,
    BASE_MOVIMIENTOS,
    BASE_TIPOBONO,
    URL_TIPOBONO,
    OBTENERBONOENTREGAS,
    BONOPORENTREGA,
    OBTNERMOVIMIENTOS,
    MOVIMIENTOSCONSULTADOS,
    IDMOVIMIENTO,
    URL_MOVIMIENTOID,
    ROL_AUXILIAR,
    URL_REPORTE,
    DATOS_REPORTE,
    URL_FECHAMOVIMIENTO,
    URL_IDSIGUIENTE
}