const START_AJAX = 'START_AJAX';
const END_AJAX = 'END_AJAX';
const INICIAR_SESION = 'INICIAR_SESION';
const VALIDAR_SESION_LOCAL = 'VALIDAR_SESION_LOCAL';
const CERRAR_SESION = 'CERRAR_SESION';
const OBTENER_TIPO_EMPLEADO ='OBTENER_TIPO_EMPLEADO';
const OBTENER_JORNADA_LABORAL = 'OBTENER_JORNADA_LABORAL';
const OBTENER_ROL = 'OBTENER_ROL';

export {
  START_AJAX,
  END_AJAX,
  INICIAR_SESION,
  VALIDAR_SESION_LOCAL,
  CERRAR_SESION,
  OBTENER_TIPO_EMPLEADO,
  OBTENER_JORNADA_LABORAL,
  OBTENER_ROL
};
