const START_AJAX = 'START_AJAX';
const END_AJAX = 'END_AJAX';
const INICIAR_SESION = 'INICIAR_SESION';
const VALIDAR_SESION_LOCAL = 'VALIDAR_SESION_LOCAL';
const CERRAR_SESION = 'CERRAR_SESION';
const OBTENER_TIPO_EMPLEADO ='OBTENER_TIPO_EMPLEADO';
const OBTENER_JORNADA_LABORAL = 'OBTENER_JORNADA_LABORAL';
const OBTENER_ROL = 'OBTENER_ROL';
const ALTA_EMPLEADO = 'ALTA_EMPLEADO';
const OBTENER_EMPLEADOS = 'OBTENER_EMPLEADOS';
const ELIMINAR_EMPLEADO = 'ELIMINAR_EMPLEADO';
const OBTENER_EMPLEADOPORID = 'OBTENER_EMPLEADOPORID';
const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO';
const ALTA_MOVIMIENTO = 'ALTA_MOVIMIENTO';
const OBTENER_TIPOBONO = 'OBTENER_TIPOBONO';
const OBTENER_MOVIMIENTOS = 'OBTENERMOVIMIENTOS';

export {
  START_AJAX,
  END_AJAX,
  INICIAR_SESION,
  VALIDAR_SESION_LOCAL,
  CERRAR_SESION,
  OBTENER_TIPO_EMPLEADO,
  OBTENER_JORNADA_LABORAL,
  OBTENER_ROL,
  ALTA_EMPLEADO,
  OBTENER_EMPLEADOS,
  ELIMINAR_EMPLEADO,
  OBTENER_EMPLEADOPORID,
  ACTUALIZAR_EMPLEADO,
  ALTA_MOVIMIENTO,
  OBTENER_TIPOBONO,
  OBTENER_MOVIMIENTOS
};
